version: '3'
services:
  wrapper0:
    container_name: ipfs_storage_cruster-wrapper0
    image: ipfs_storage_cruster/ipfs_node_wrapper:latest
    depends_on:
      - ipfs0
    environment:
      IPFS_GATEWAY_ADDRESS: "ipfs0:8080"
      IPFS_RPC_ADDRESS: "ipfs0:5001"
    ports:
      - "3000:3000"
      - "4000:4000"

  ipfs0:
    container_name: ipfs_storage_cruster-ipfs0
    image: ipfs/kubo:release
    ports:
     - "8080:8080" # ipfs gateway
     - "5001:5001" # ipfs rpc api
    volumes:
      - ./compose/ipfs0:/data/ipfs
