version: '3'
services:
  # ===== Manager =====
  manager:
    container_name: ipfs_storage_cruster-manager
    image: ipfs_storage_cruster/ipfs_storage_cruster_manager:latest
    depends_on:
      - master-ipfs
      - manager-mysql
    environment:
      APP_LOG: "trace,hyper=debug"
      APP_DATABASE_URL: "mysql://root:1234@manager-mysql/ipfs_storage_cruster_manager"
      APP_IPFS_RPC_ADDRESS: "master-ipfs:5001"
      APP_IPFS_SWARM_MULTI_ADDRESS: "/dns/master-ipfs/tcp/4001"
    ports:
      - "5000:5000" # server

  master-ipfs:
    container_name: ipfs_storage_cruster-master-ipfs
    image: ipfs/kubo:release
    ports:
      - "8080:8080" # ipfs gateway
      - "5001:5001" # ipfs rpc api
      - "4001:4001" # ipfs swarm
    volumes:
      - ./compose/master-ipfs:/data/ipfs
      - ./scripts/ipfs_clear_bootstrap.sh:/container-init.d/ipfs_clear_bootstrap.sh

  # ===== Node 0 =====
  wrapper-0: # TODO 新加节点时，manager主动让wrapper0连接到其对应的IPFS node，从而减少配置复杂度
    container_name: ipfs_storage_cruster-wrapper-0
    image: ipfs_storage_cruster/ipfs_node_wrapper:latest
    depends_on:
      - slave-ipfs-0
    environment:
      APP_LOG: "trace,hyper=debug"
      APP_IPFS_GATEWAY_ADDRESS: "slave-ipfs-0:8080"
      APP_IPFS_RPC_ADDRESS: "slave-ipfs-0:5001"
    ports:
      - "3000:3000" # public
      - "4000:4000" # admin

  slave-ipfs-0:
    container_name: ipfs_storage_cruster-slave-ipfs-0
    image: ipfs/kubo:release
    ports:
      - "8081:8080" # ipfs gateway
      - "5002:5001" # ipfs rpc api
    volumes:
      - ./compose/slave-ipfs-0:/data/ipfs
      - ./scripts/ipfs_clear_bootstrap.sh:/container-init.d/ipfs_clear_bootstrap.sh

  # ===== Database =====
  manager-mysql:
    container_name: ipfs_storage_cruster-manager-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ipfs_storage_cruster_manager
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./sql/ipfs_storage_cruster_manager.sql:/docker-entrypoint-initdb.d/ipfs_storage_cruster_manager.sql # init sql
#      - ./compose/manager-mysql/init/:/docker-entrypoint-initdb.d/
      - ./compose/manager-mysql/conf/:/etc/mysql/conf.d/
      - ./compose/manager-mysql/data/:/var/lib/mysql/
    command:
#      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
