//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "node_status")]
pub enum NodeStatus {
    #[sea_orm(string_value = "online")]
    Online,
    #[sea_orm(string_value = "unhealthy")]
    Unhealthy,
    #[sea_orm(string_value = "offline")]
    Offline,
}
